### ISSUE TITLE
Collect and graph fish prices (grimsby)

### ISSUE THREAD

**Issue by andreaseliasson** [comp6234-group5/fish#1]

**Comment by charlienewey** [comment]
[haddock_cod_2016.zip](https://github.com/comp6234-group5/fish/files/677066/haddock_cod_2016.zip)

**Comment by charlienewey** [comment]
Both Haddock and Cod appear to take a really significant drop in price during the weeks surrounding the referendum (e.g. weeks beginning 24/06/16). This could be due to the fall in value of the pound or some external factors (difficult to tell).
