### ISSUE TITLE
Collect and graph fishing companies' stock values

### ISSUE THREAD

**Issue by andreaseliasson** [comp6234-group5/fish#4]

**Comment by charlienewey** [comment]
[scottish-salmon-company-prices.zip](https://github.com/comp6234-group5/fish/files/674613/scottish-salmon-company-prices.zip)

Prices dataset [from Yahoo](http://finance.yahoo.com/quote/SSC.OL/history?p=SSC.OL)

**Comment by charlienewey** [comment]
Volume traded shoots up really high after the referendum, as well as the individual share price. This would suggest a significant surge in speculative trading activity due to Brexit.

**Comment by charlienewey** [comment]
Finished, in `wip_charlie` branch.
